use mmfunction and _report function

diff --git a/makedn b/makedn
--- a/makedn
+++ b/makedn
@@ -1,5 +1,8 @@
 #!/bin/bash
 
+SCRIPTDIR=$(dirname $(which "${0}"))
+. "${SCRIPTDIR}/mmfunctions" || { echo "Missing '${SCRIPTDIR}/mmfunctions'. Exiting." ; exit 1 ;};
+
 DN_DATE=$(date +%Y-%m%d)
 MEDIA_ID="DN${DN_DATE/-}"
 
@@ -22,24 +25,24 @@ SCC_ONLINE=$(_validate_url "${SCC_FILE}")
 
 if [[ "${MP4_ONLINE}" == "true" && "${SCC_ONLINE}" == "true" ]] ; then
     #download
-    echo "DN files for ${DN_DATE} are online. Processing files in ${PROCESS_DIR}."
-    echo "Downloading Democracy Now SCC"
+    _report -dt "DN files for ${DN_DATE} are online. Processing files in ${PROCESS_DIR}."
+    _report -dt "Downloading Democracy Now SCC"
     wget "${SCC_FILE}" -O "${PROCESS_DIR}/${MEDIA_ID}.scc"
-    echo "Downloading Democracy Now MP4"
+    _report -dt "Downloading Democracy Now MP4"
     wget "${MP4_FILE}" -O "${PROCESS_DIR}/${MEDIA_ID}.mp4"
-    echo "Running makebroadcast on ${MEDIA_ID}.mp4"
+    _report -dt "Running makebroadcast on ${MEDIA_ID}.mp4"
 
     #transcode
     makebroadcast "${PROCESS_DIR}/${MEDIA_ID}.mp4"
 
     #deliver
-    echo "Delivering mov to Omneon"
+    _report -dt "Delivering mov to Omneon"
     uploadomneon "${PROCESS_DIR}/service/${MEDIA_ID}.mov"
-    echo "Delivering scc to Omneon"
+    _report -dt "Delivering scc to Omneon"
     uploadomneon "${PROCESS_DIR}/${MEDIA_ID}.scc"
 
     # cleanup
-    echo "Cleaning up temporary files."
+    _report -dt "Cleaning up temporary files."
     rm -v "${PROCESS_DIR}/service/${MEDIA_ID}.mov"
     rm -v "${PROCESS_DIR}/${MEDIA_ID}.scc"
     rm -v "${PROCESS_DIR}/${MEDIA_ID}.mp4"
@@ -48,9 +51,9 @@ if [[ "${MP4_ONLINE}" == "true" && "${SCC_ONLINE}" == "true" ]] ; then
     _email_delivery "${MAKEYOUTUBE_DELIVERY_EMAIL_TO}"
 else
     if [[ "${MP4_ONLINE}" != "true" ]] ; then
-        echo "The MP4 file for ${DN_DATE} is not online at https://www.democracynow.org/static yet."
+        _report -wt "The MP4 file for ${DN_DATE} is not online at https://www.democracynow.org/static yet."
     fi
     if [[ "${SCC_ONLINE}" != "true" ]] ; then
-        echo "The SCC file for ${DN_DATE} is not online at https://www.democracynow.org/static yet."
+        _report -wt "The SCC file for ${DN_DATE} is not online at https://www.democracynow.org/static yet."
     fi
 fi
