storagereport: internal functions

diff --git a/storagereport b/storagereport
--- a/storagereport
+++ b/storagereport
@@ -2,6 +2,91 @@
 scriptdir=$(dirname "$0")
 . "$scriptdir/mmfunctions" || { echo "Missing '$scriptdir/mmfunctions'. Exiting." ; exit 1 ;};
 
+# internal functions
+_get_iso8601(){
+    date +%FT%T
+}
+_log(){
+    MMLOGNAME="mm.log"
+    MMLOGDIR="${CUSTOM_LOG_DIR:-/tmp}"
+    MMLOGFILE="${MMLOGDIR}/${MMLOGNAME}"
+    if [ ! -d "${MMLOGDIR}" ] ; then
+        _mkdir2 "${MMLOGDIR}"
+        if [ "${?}" -ne 0 ]; then
+            echo "${0}: Can't create log directory at ${MMLOGDIR}, exiting... Use mmconfig to change logging directory."
+            exit 1
+        fi
+    fi
+    OPTIND=1
+    while getopts ":beac" OPT; do
+        case "${OPT}" in
+            b) STATUS="start" ;;              # script is beginning
+            e) STATUS="end"   ;;              # script is ending
+            a) STATUS="abort" ;;              # script is aborted
+            c) STATUS="comment" ;;            # comment about what script is doing
+            w) STATUS+"warning" ;;            # warning information
+        esac
+    done
+    shift $(( ${OPTIND} - 1 ))
+    NOTE="${1}"
+    echo $(_get_iso8601)", $(basename "${0}"), ${STATUS}, ${OP}, ${MEDIAID}, ${NOTE}" >> "${MMLOGFILE}"
+}
+_mkdir2(){
+    local DIR2MAKE=""
+    while [ "${*}" != "" ] ; do
+        DIR2MAKE="${1}"
+        if [ ! -d "${DIR2MAKE}" ] ; then
+            mkdir -p "${DIR2MAKE}"
+            if [ "${?}" -ne 0 ]; then
+                _report -wt "${0}: Can't create directory at ${DIR2MAKE}"
+                exit 1
+            fi
+        fi
+        shift
+    done
+}
+_report(){
+    local RED="$(tput setaf 1)"   # Red      - For Warnings
+    local GREEN="$(tput setaf 2)" # Green    - For Declarations
+    local BLUE="$(tput setaf 4)"  # Blue     - For Questions
+    local NC="$(tput sgr0)"       # No Color
+    local COLOR=""
+    local STARTMESSAGE=""
+    local ENDMESSAGE=""
+    local ECHOOPT=""
+    local LOG_MESSAGE=""
+    OPTIND=1
+    while getopts ":qdwstn" OPT; do
+        case "${OPT}" in
+            q) COLOR="${BLUE}" ;;                         # question mode, use color blue
+            d) COLOR="${GREEN}" ;;                        # declaration mode, use color green
+            w) COLOR="${RED}" ; LOG_MESSAGE="Y";;                 # warning mode, use color red
+            s) STARTMESSAGE+=([$(basename "${0}")] ) ;;     # prepend scriptname to the message
+            t) STARTMESSAGE+=($(_get_iso8601) '- ' ) ;;     # prepend timestamp to the message
+            n) ECHOOPT="-n" ;;                          # to avoid line breaks after echo
+        esac
+    done
+    shift $(( ${OPTIND} - 1 ))
+    MESSAGE="${1}"
+    echo "${ECHOOPT}" "${COLOR}${STARTMESSAGE[@]}${MESSAGE}${NC}"
+    [ "${LOG_MESSAGE}" = "Y" ] && _log -w "${MESSAGE}"
+}
+_check4mount(){
+    # check to see if a requested volume is mount and warn if not
+    local VOLUME=""
+    while [ "${*}" != "" ] ; do
+        VOLUME="${1}"
+        if [ $(mount | grep -c ${VOLUME}) = 0 ] ; then
+            echo
+            echo
+            _report -wt "Please connect to ${VOLUME} on $(uname -n)"
+            echo
+            echo
+        fi
+        shift
+    done
+}
+
 ## local variables
 # declare an age in days under which files will be excluded from being removal candidates
 keepnewforXdays=7
